# This is a basic workflow to help you get started with Actions

name: Snake

# Controls when the workflow will run
on:
  schedule: # execute every 12 hours
    - cron: "34 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: chriskthomas
          svg_out_path: snake.svg
